### PR TITLE
Update remote write protocol to version 0.1.0

### PR DESCRIPTION
**Pull request by juliusv**
This also extends the end-to-end test to cover the HTTP handling and protocol encoding/decoding, to verify that we handle the new protocol correctly. Also, vendoring updates that are needed to make that happen.

Fixes https://github.com/ChronixDB/chronix.ingester/issues/9
Fixes https://github.com/ChronixDB/chronix.ingester/issues/10

### CODE REVIEW

**Comment by juliusv** [comment]
@FlorianLautenschlager I'm not sure why dependency-ci is complaining about `gopkg.in/gemnasium/logrus-airbrake-hook.v2` being unlicensed, especially since `vendor/gopkg.in/gemnasium/logrus-airbrake-hook.v2/LICENSE` exists. Can we somehow add an exception, remove dependency-ci (if it doesn't work properly), or fix it another way?

**Comment by FlorianLautenschlager** [comment]
Hi @juliusv i am fine with removing the dependency-ci extension. But first we should check if we can add an exception for gopkg.in/gemnasium/logrus-airbrake-hook.v2.

**Comment by juliusv** [comment]
Ah, I used the original way to vendor things again now (`gvt` instead of `govendor`) and now it doesn't even run dependency-ci? Anyways, things seem to look good now.

**Comment by juliusv** [comment]
Oh, now dependency-ci showed up again as failed (it wasn't visible at all at first)... hmm!

**Review by FlorianLautenschlager — APPROVED** [review]
Seems good to me.

**Comment by FlorianLautenschlager** [comment]
I have disabled dependency-ci for this project.

**Pull request merged**
